language: java
sudo: true
dist: trusty
jdk: oraclejdk11
matrix:
  allow_failures:
    - jdk: openjdk-ea
addons:
  apt:
    packages:
      - oracle-java11-installer
before_script:
  - chmod a+x ./mvnw